DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'twiniti_app') THEN
    CREATE ROLE twiniti_app NOLOGIN NOBYPASSRLS;
  END IF;
END $$;
--> statement-breakpoint

ALTER ROLE twiniti_app NOBYPASSRLS;
GRANT USAGE ON SCHEMA public TO twiniti_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO twiniti_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO twiniti_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO twiniti_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO twiniti_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO twiniti_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO twiniti_app;
GRANT twiniti_app TO neondb_owner;
